name: "Backup Databases"
description: "Backup databases to S3"
inputs:
  DB_USER:
    description: "Database username"
    required: true
    default: ""

  DB_PASSWORD:
    description: "Database password"
    required: true
    default: ""

  DB_HOST:
    description: "Database host"
    required: true
    default: ""

  DATABASES:
    description: 'Databases to backup (e.g. ("example_1" "example_2") or () to backup all databases)'
    required: false
    default: "()"

  IGNORED_DATABASES:
    description: 'Databases to ignore (e.g. ("example_3" "example_4") or () to not ignore any databases)'
    required: false
    default: "(Database mysql information_schema performance_schema cond_instances)"

  S3_BUCKET_NAME:
    description: "S3 bucket name (e.g. database-backups)"
    required: true
    default: ""

  S3_FOLDER:
    description: "S3 folder name (e.g. databases/production)"
    required: true
    default: ""

  AWS_ACCESS_KEY_ID:
    description: "AWS access key"
    required: true
    default: ""

  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret key"
    required: true
    default: ""

  AWS_REGION:
    description: "AWS region (e.g. eu-central-1)"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    DB_USER: ${{ inputs.DB_USER }}
    DB_PASSWORD: ${{ inputs.DB_PASSWORD }}
    DB_HOST: ${{ inputs.DB_HOST }}
    DATABASES: ${{ inputs.DATABASES }}
    IGNORED_DATABASES: ${{ inputs.IGNORED_DATABASES }}
    S3_BUCKET_NAME: ${{ inputs.S3_BUCKET_NAME }}
    S3_FOLDER: ${{ inputs.S3_FOLDER }}
    AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ inputs.AWS_REGION }}
